import React from 'react'

export default function Home() {
  const typeDesc = JSON.stringify(themeJSONformat, null, '\t')
  console.log(typeDesc)
  return (
    <div>
      Home route should show the create a theme portion of the app. If you're
      not able to write the mutuation to post to the database then just work on
      fetching color schemes from http://colormind.io/api/ and font pairings
      from an api that looks easy to work with. The data should be in the
      following format for posting to the database. Check console for type
      definition.
    </div>
  )
}

const themeJSONformat = {
  id:
    'autogenerated by prisma, only need to send if updating an exisiting theme',
  title: 'String',
  colors: {
    id:
      'autogenerated by prisma, only need to send if updating an exisiting color pallete',
    title: 'only required if you want to save color pallete, else leave blank',
    primaryLight:
      'Hex color code from first color value returned from colormind',
    accentLight:
      'Hex color code from second color value returned from colormind',
    accentBrand:
      'Hex color code from third color value returned from colormind',
    accentDark:
      'Hex color code from fourth color value returned from colormind',
    primaryDark: 'Hex color code from fifth color value returned from colormind'
  },
  fonts: {
    id:
      'autogenerated by prisma, only need to send if updating an exisiting font pairing',
    title: 'only required if you want to save font pairing, else leave blank',
    primary: 'css font family name',
    secondary: 'css font famaily name'
  }
}
